import { motion } from 'motion/react';

export default function Terms() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="prose prose-invert prose-blue max-w-none"
      >
        <h1 className="text-3xl font-bold text-white mb-8">Terms & Conditions</h1>
        
        <div className="text-muted text-sm mb-8 space-y-4">
          <p>Last Updated: {new Date().toLocaleDateString()}</p>
          <p>These terms and conditions outline the rules and regulations for the use of Sayam's applications (MindLock and AssignMate), operated by Ganesh Rathore.</p>
        </div>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-4">1. License and Use</h2>
          <div className="text-muted space-y-4 text-sm leading-relaxed">
             <p>By accessing these products, you are granted a limited, non-exclusive, non-transferable license to use the services in accordance with these Terms.</p>
             <p><strong>Acceptable Use:</strong> You agree not to misuse our services, reverse-engineer our applications, or use them for any illegal activities.</p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-4">2. Payments & Pricing</h2>
          <div className="text-muted space-y-4 text-sm leading-relaxed">
             <p>All prices are listed in Indian Rupees (INR) unless otherwise stated. We use Razorpay to process payments securely.</p>
             <p><strong>MindLock:</strong> Subscriptions are billed periodically (monthly or yearly). You may cancel your subscription at any time.</p>
             <p><strong>AssignMate:</strong> Documents are charged strictly on a per-document, pay-as-you-go basis, scaling with page count.</p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-4">3. Intellectual Property</h2>
          <div className="text-muted space-y-4 text-sm leading-relaxed">
             <p>The applications, their structural code, templates, and UI are intellectual property of Ganesh Rathore. Output documents generated by AssignMate become your property upon successful payment, subject to any underlying template licensing.</p>
          </div>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold text-white mb-4">4. Limitation of Liability</h2>
          <div className="text-muted space-y-4 text-sm leading-relaxed">
             <p>In no event shall Ganesh Rathore be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the services.</p>
          </div>
        </section>
      </motion.div>
    </div>
  );
}
